spring.application.name=taskapp
spring.profiles.active=dev


jwt.secret=test-secret-key-test-secret-key-12345
jwt.expiration=3600000


# Show SQL queries in console
spring.jpa.show-sql=true

# Format SQL nicely (easier to read)
spring.jpa.properties.hibernate.format_sql=true

# Show actual parameter values (VERY IMPORTANT)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE