package com.nick.taskapp.model;

import java.time.LocalDate;
import java.time.LocalDateTime;

import jakarta.persistence.*;



/*
 * Represents a Task entity stored in the database.
 *
 * Mapped by JPA to a table where each instance is a row.
 * Defines the structure of task data persisted and retrieved.
 */
@Entity
public class Task {
    /*
     * Primary key of the task.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /*
     * Priority level of the task (HIGH, MEDIUM, LOW).
     * Stored as a String in the database.
     */
    @Enumerated(EnumType.STRING)
    private Priority priority;
    
    /*
     * Title of the task.
     * Must not be blank (validated at API layer).
     */
    private String title;

    /*
     * Due date of the task.
     * Must not be null.
     */
    private LocalDate dueDate;
    
    /*
     * Indicates whether the task is completed.
     */
    private boolean completed;
    
    //auditfields: Track when a record was created and last updated.
    /*
     * Timestamp when the task was last created/updated.
     */
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    //Lifecycle Hooks
    /*
     * Automatically sets timestamps before the entity is first saved.
     */
    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    /*
     * Automatically updates the updatedAt timestamp before saving changes.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = LocalDateTime.now();
    }


    /*
     * Required no-args constructor for JPA and JSON deserialization.
     */
    public Task() {
    }

    public Task(Long id, String title, boolean completed, Priority priority, LocalDate dueDate) {
        this.id = id;
        this.title = title;
        this.completed = completed;
        this.priority = priority;
        this.dueDate = dueDate;
    }

    // getters and setters

    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }
    public void setTitle(String title) {
        this.title = title;
    }

    public boolean isCompleted() {
        return completed;
    }
    public void setCompleted(boolean completed) {
        this.completed = completed;
    }

    public Priority getPriority() {
        return priority;
    }

    public void setPriority(Priority priority) {
        this.priority = priority;
    }

    public LocalDate getDueDate() {
        return dueDate;
    }

    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}


/*
The shape of your data and how Spring reads/writes it
*/

/*
Database model. 
Defines:
what a task looks like
how it is stored
how JPA reads/writes it

So in simple terms:
Java object <-> database row
JPA is the translator

You use JPA annotations
Hibernate translates to SQL


3 main jobs:
defines the shape of your data in Java. task has id, title, etc...: what columns/values does a task have\
tells JPA/Hibernate how to map that data: thats what the annotations are for. @Entity: class should be treated like a databse-backed object. etc etc.
gives Hibernate access to the data: hibernate needs to create objects fill in values from DB results, read values when saving. what getters/setters and no-args constructor for.

This file contains the JPA annotations that Hibernate reads so it knows how to map the class to the database.

Persisted = saved to the database (permanently stored)

*/