package com.nick.taskapp.model;

import jakarta.persistence.*;
/*
 * Represents an application user stored in the database.
 *
 * Used for authentication by storing a unique username
 * and a hashed password.
 */
@Entity
@Table(name = "users")
public class User {
    /*
     * Primary key of the user.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /*
     * Unique username used for login.
     */
    @Column(unique = true, nullable = false)
    private String username;
    
    /*
     * Hashed password used for authentication.
     *
     * Never store raw/plain-text passwords.
     */
    @Column(nullable = false)
    private String password;
    
    /*
     * Required no-args constructor for JPA.
     */
    public User() {
    }

    public User(Long id, String username, String password) {
        this.id = id;
        this.username = username;
        this.password = password;
    }

    public Long getId() {
        return id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}

/*
User represents an application user stored in the database.

It is used for authentication, meaning:

registering a user
storing their username
storing their hashed password
finding them later during login

This is your auth-side entity, similar to how Task is your task-side entity.


1. Entity mapping
@Entity
@Table(name = "users")
This tells JPA/Hibernate that this class maps to the users table.
2. Primary key generation
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
The database automatically generates the user id.
3. Column constraints
@Column(unique = true, nullable = false)
This tells the database:
username must be unique
username cannot be null
password cannot be null
4. Password persistence
The password field stores the hashed password, not the raw password.
That part happens in AuthService.
*/